# Generated by Django 4.2.13 on 2024-07-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$6wGHh4LMsJtV7oZtw6Dm4h$+prG5SVmMW4pEj9lRIqg8uKHy5YOu1xJtUIm93nSUhE=', max_length=128),
        ),
    ]
