# Generated by Django 4.2.13 on 2024-07-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$LzWL2eN7i86KJx70J8ZXOQ$09BKpB17zpsxeRcMu7Q8dSIYZJnm8K72PKelDJbQ4aQ=', max_length=128),
        ),
    ]
